[build]
dockerfilePath = "Dockerfile.prod"

[deploy]
startCommand = "sh entrypoint.sh"
healthcheckPath = "/health"
healthcheckTimeout = 60
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
